#include "protheus.ch" 

/*
|-----------------------------------------------------------------------------------------------|	
|	Programa : IFINA15			  		| 	Fevereiro de 2015				  					|
|-----------------------------------------------------------------------------------------------|
|	Desenvolvido por Rubens Cruz - Anadi														|
|-----------------------------------------------------------------------------------------------|	
|	Descrição : Cadastro de Instruções Bancárias X Instrucoes Sistema						  	|
|-----------------------------------------------------------------------------------------------|	
*/
                        

user Function IFINA15()

	axCadastro("Z27","Cadastro de Instruções Bancárias X Instrucoes Sistema")

return 